### PR TITLE
Remove lut field from mm_np struct.

### PR DESCRIPTION
**Pull request by segalmax**

### CODE REVIEW

**Comment by yosefm** [comment]
How do you even run the tests? check_imgcoord does not compile because it addresses the lut field. I think you are working off an outdated version, so maybe rebase on the latest master. Anyway I'll try to test again against your base, but for final merging you'll need that rebase.

**Comment by yosefm** [comment]
Ok, the problem with "multimed_nlay stopped after 40 iterations" stems from calling a buggy version of get_mmf_from_mmlut which is fixed in latest master. It overwrites the pos variable.

More important, it is called because init_mmlut calls multimed_r_nlat which checks mmlut.data. At this point it is already allocated in memory but not initialized, so we get a bad situation. The initialization in init_mmlut shoud first allocate the memory to a temporary variable and only after init is done, point mmlut.data to that memory.

After this is fixed, test still fail but I trust you would find out why.

**Comment by yosefm** [comment]
There are several uses of lut in the parameters branch we merge separately, so we can't yet merge this branch on top of the current master. Please merge current master into your remove_lut branch, solve testing errors, and push back the changes.

**Comment by segalmax** [comment]
I didn't quite understand what you mean.
Should I merge my remove_lut branch with your master or openptv's master?
I remember that currently, there are no testing errors in remove_lut, so do
you mean that errors will occur after I'll merge with current master?

Max.

**Comment by yosefm** [comment]
The one with the parameters bindings merge.
Anyway, I just updated my master and it's the same as OpenPTV master, so no problem here.
Yes, errors will occur after the merge because the merged code has the lut field.

**Comment by yosefm** [comment]
Sent upstream. Well done.
https://github.com/OpenPTV/openptv/pull/79

**Pull request closed without merging**
