### PR TITLE
Paramsb

### PR DESCRIPTION
**Pull request by segalmax**
PR with parameters related bindings and tests.

### CODE REVIEW

**Comment by alexlib** [comment]
Can we merge this one to OpenPTV soon?

**Comment by yosefm** [comment]
Ok, I'm trying to merge but it's making too much of a mess because of all the janitoring and whitespace changes. Max, please take *only* the shaping parameters changes, do them again on a clean branch based on OpenPTV/openptv:master, and resubmit (make sure the tests still pass).

**Comment by segalmax** [comment]
Done.

**Comment by yosefm** [comment]
This was merged to upstream.

**Pull request closed without merging**
