### PR TITLE
Update parameters.h

### PR DESCRIPTION
**Pull request by KobiPesach**

### CODE REVIEW

**Comment by alexlib** [comment]
Is there an update on this pull request?  Shall we review it? Can we meet soon to see whether we're progressing?

**Comment by yosefm** [comment]
We are doing a lot of groundwork behind the scenes, to help Kobi and Max understand better the development process and the software in general.

Perhaps we should close this PR and let Kobi resubmit when he's prepared.

**Comment by alexlib** [comment]
Thanks for the update. Looking forward

**Comment by KobiPesach** [comment]
A pull request for those files :
parameters.c
parameters.h
check_parameters.c

**Comment by yosefm** [comment]
I'm closing this in favor  of the later PR.

**Pull request closed without merging**
